In [2]:
import numpy as np

In [3]:
#1. NumPy program to convert Fahrenheit degree to centigrade degree.

fht = np.array([100,98.4,91.50,99.78,101.5])
degree=np.array([])
for temp in fht:
    degreeval=(temp-32)*(5/9)
    degree = np.append(degree,degreeval)
print("Degree array",degree)

Degree array [37.77777778 36.88888889 33.05555556 37.65555556 38.61111111]


In [4]:
#2.  create a random array with 1000 elements and compute the 
# average, variance, standard deviation of the array elements
arr =  np.array([23,55,29,56,28,86,12])
mean = np.mean(arr)
variance = np.var(arr)
std = np.std(arr)

print("Mean=",mean," Variance=",variance," Standard deviation= ",std)

Mean= 41.285714285714285  Variance= 560.4897959183673  Standard deviation=  23.674665698133253


In [5]:
# 3. NumPy program to convert angles from degrees to radians for all elements in a 
# given array
degrees = np.array([32,40,180,360,45,93])
radians  = np.deg2rad(degrees)
print("Degrees = ",degrees)
print("Radian value =",radians)

Degrees =  [ 32  40 180 360  45  93]
Radian value = [0.55850536 0.6981317  3.14159265 6.28318531 0.78539816 1.6231562 ]


In [10]:
# 4.NumPy program to calculate the difference between neighbouring elements, 
# element-wise of a given array. 
arr = np.array([12,34,6,28,46,90,3])
diffs =  np.diff(arr)
print("Array",arr)
print("Difference",diffs)


Array [12 34  6 28 46 90  3]
Difference [ 22 -28  22  18  44 -87]


In [12]:
# 5.NumPy program to sort a given complex array using the real part first, then the 
# imaginary part.
arr = np.array([complex(7,5),complex(4,3),complex(12,2),complex(1,8),complex(1,9)])
sorted = np.sort(arr)
print("Array before sorting=",arr)
print("After sorting=",sorted)

Array before sorting= [ 7.+5.j  4.+3.j 12.+2.j  1.+8.j  1.+9.j]
After sorting= [ 1.+8.j  1.+9.j  4.+3.j  7.+5.j 12.+2.j]


In [6]:
#  6.NumPy program to create a 1D array with random numbers and print the values 
# greater than 4
arr=np.random.randint(low=-40,high=40,size=10)
print(arr)
res =np.where(arr > 4)
print("Elements greater than 4")
for ele in res:
    print(arr[res])


[ 25  16  15   4  24 -15   3   6 -34 -29]
Elements greater than 4
[25 16 15 24  6]


In [41]:
#7.NumPy program to create a 1D array with random numbers and
#  search a particular number given by the user.
arr=np.random.randint(low=-10, high=40, size=10)
print(arr)
num=int(input("Enter a number"))
res=np.where(arr==num)
if(len(res[0])==0):
    print("Number is not present ")
else:
    print("Number is present ")


[36 15  8  9  2 19 24 25 24 33]
Number is not present 


In [ ]:
# 8. NumPy program to save a given array to a text file and load it
arr = np.array([4,5,4,6,11,2235,56])
np.savetxt(fname="test.txt",X=arr)
np.loadtxt(fname="test.txt")

array([   4.,    5.,    4.,    6.,   11., 2235.,   56.])

In [37]:
# 9.NumPy program to create an array of all the even integers from 30 to 60.
arr =  np.arange(30,61,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [39]:
# 10.  NumPy program to compute sum of all elements ,sum of each column and sum of
# each row of a given array.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Sum of all elements
total_sum = np.sum(arr)
print("Sum=",total_sum)
# Sum of each column (axis=0)
col_sum = np.sum(arr, axis=0)
print("Cols sum=",col_sum)
# Sum of each row (axis=1)
row_sum = np.sum(arr, axis=1)
print("Row sum=",row_sum)

Sum= 45
Cols sum= [12 15 18]
Row sum= [ 6 15 24]
