In [38]:
import numpy as np
from numpy import linalg

In [39]:
def matrixread(n):
    matrix = [] 
    for i in range(0,n):
        temp=[]
        for j in range(0,n):
            num=int(input("Enter element "+str(i)+","+str(j)))
            temp.append(num)
        matrix.append(temp)
    return matrix

In [40]:
n=int(input("Enter the order of the matrix")) #defining a matrix
print("Matrix 1")
matrix1=np.array(matrixread(n))
print("Matrix 2")
matrix2=np.array(matrixread(n))
print("Matrices are")
print(matrix1)
print(matrix2)

Matrix 1
Matrix 2
Matrices are
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 12 33]
 [23 12 56]
 [32 45 27]]


In [41]:
print(np.transpose(matrix1)) #2. Transpose of matrix


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [42]:
print(np.trace(matrix1)) #3. Trace - sum of diagonal elements


15


In [43]:
print(np.dot(matrix1,matrix2)) #1. dot product of 2 matrices


[[154 171 226]
 [355 378 574]
 [556 585 922]]


In [44]:
print(linalg.inv(matrix1)) #6. inverse of a matrix


[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [45]:
print(linalg.matrix_rank(matrix1)) # 4. rank of matrix


2


In [46]:
print(linalg.eig(matrix1)) # 7. eigen values and eigen vectors

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [47]:
print(linalg.det(matrix1)) # 5. determinant of matrix

-9.51619735392994e-16
