In [27]:
import numpy as np
from numpy import linalg

In [28]:
def matrixread(n):
    matrix = [] 
    for i in range(0,n):
        temp=[]
        for j in range(0,n):
            num=int(input("Enter element "+str(i)+","+str(j)))
            temp.append(num)
        matrix.append(temp)
    return matrix

In [29]:
n=int(input("Enter the order of the matrix")) #defining a matrix
print("Matrix 1")
matrix1=np.array(matrixread(n))
print("Matrix 2")
matrix2=np.array(matrixread(n))
print("Matrices are")
print(matrix1)
print(matrix2)

Matrix 1
Matrix 2
Matrices are
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 13 12]
 [33 12 67]
 [34 22 18]]


In [30]:
print(np.transpose(matrix1)) #2. Transpose of matrix


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [31]:
print(np.trace(matrix1)) #3. Trace - sum of diagonal elements


15


In [32]:
print(np.dot(matrix1,matrix2)) #1. dot product of 2 matrices


[[180 103 200]
 [417 244 491]
 [654 385 782]]


In [33]:
print(linalg.inv(matrix1)) #6. inverse of a matrix


[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [34]:
print(linalg.matrix_rank(matrix1)) # 4. rank of matrix


2


In [36]:
print(linalg.eig(matrix1)) # 7. eigen values and eigen vectors

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
