In [ ]:
import numpy as np


In [2]:
data=np.array([
 1,2,3,4
])
print(type(data))

<class 'numpy.ndarray'>


In [ ]:
vals=np.arange(2,90,2) # arange(begin,end,stepsize) creates an array from numbers
print(vals)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]
[18 14 10]


In [4]:
vals=np.zeros(15) #creates an array of 15 zeroes
print(vals)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
vals=np.ones(10)
print(vals)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
vals=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vals)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
vals=np.identity(3) # 3x3 identity matrix
print(vals)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
vals=np.arange(1,5)
copy=np.copy(vals)
copy[1]=700
print (vals)
print(copy)


[1 2 3 4]
[  1 700   3   4]


In [26]:
a=[[1,2,3,4,5],[1,2,3,4,5]]
b=[[6,7,8,9,10],[6,7,8,9,10]]
c=np.concatenate([a,b]) #horizontal joining
print(c)
c=np.concatenate([a,b],axis=1)#vertical joining
print(c)

[[ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
vals=np.array([9,5,4,31,10,12])
indices=np.where(vals>10)# returns indices of elements > 10
print(indices)
for i in range(0,len(vals)):#printing other values
    if i not in indices[0]:
        print(vals[i])

(array([3, 5], dtype=int64),)
9
5
4
10
